# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "btrfs" "hid_apple" ];
  boot.kernelModules = [ "kvm-intel" "wl" "fbcon" "mba6x_bl" ];
  boot.extraModulePackages = with config.boot.kernelPackages;
                             [ broadcom_sta mba6x_bl ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.devices = [
    { name = "enc-partvol";
      device = "/dev/sda4";
      preLVM = true;
    }
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b2029c9a-371b-4182-9e44-676d69cb1604";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/67E3-17ED";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/90f4409c-f1ae-439d-8bcd-88048726de08"; }
    ];

  nix.maxJobs = 4;
  nix.buildCores = 4;

  services = {
    tlp.extraConfig = ''
      CPU_SCALING_GOVERNOR_ON_AC=performance
      CPU_SCALING_GOVERNOR_ON_BAT=powersave
    
      CPU_BOOST_ON_AC=1
      CPU_BOOST_ON_BAT=0

      DEVICES_TO_DISABLE_ON_STARTUP="bluetooth"
      DISK_IOSCHED="deadline"
    '';
#    xserver.multitouch.enable = true;
    xserver.libinput.enable = true;
  };

  hardware.bluetooth.enable = true;
}
