# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "btrfs" ];
  boot.kernelModules = [ "kvm-intel" "wl" "fbcon" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "i915.i915_enable_rc6=0" ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.luks.devices = [
    { name = "enc-pv";
      device = "/dev/sda2";
      preLVM = true;  
    }
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e035e85e-d5b3-43d8-a7c7-98ded31f6123";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9892-A789";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8980828c-6304-4ca9-88ca-34f515cd20ba"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  nix.buildCores = 4;

  services = {
    tlp.extraConfig = ''
      CPU_SCALING_GOVERNOR_ON_AC=performance
      CPU_SCALING_GOVERNOR_ON_BAT=powersave

      CPU_BOOST_ON_AC=1
      CPU_BOOST_ON_BAR=0

      DEVICES_TO_DISABLE_ON_STARTUP="bluetooth"
      DISK_IOSCHED="deadline deadline"
    '';
    xserver.libinput.enable = true;
  };

  hardware.bluetooth.enable = false;
}
